[package]
name = "nvelope"
version = "0.1.2"
edition = "2021"

[dependencies]
dcbor = "0.9.0"
# dcbor = { path = "../dcbor" }

bc-ur = "0.2.0"
# bc-ur = { path = "../bc-ur" }

# bc-envelope = "0.6.0"
bc-envelope = { path = "../bc-envelope" }

bc-components = "0.5.0"
# bc-components = { path = "../bc-components" }

clap = { version = "4.4.3", features = ["derive", "unstable-styles"] }
anyhow = "1.0"
anstyle = "1.0.1"
hex = "0.4.3"
regex = "1.9.5"

[dev-dependencies]
assert_cmd = "2.0.12"
indoc = "2.0.0"
