[package]
name = "envelope"
version = "0.3.0"
edition = "2021"
description = "Gordian Envelope Command Line Tool."
authors = ["Blockchain Commons"]
keywords = ["encoding", "cbor", "binary", "format", "serialization"]
repository = "https://github.com/BlockchainCommons/bc-envelope-cli-rust"
readme = "README.md"

[dependencies]
dcbor = "0.9.0"
# dcbor = { path = "../dcbor" }

bc-ur = "0.2.0"
# bc-ur = { path = "../bc-ur" }

bc-envelope = "0.9.0"
# bc-envelope = { path = "../bc-envelope" }

bc-components = "0.5.0"
# bc-components = { path = "../bc-components" }

clap = { version = "4.4.3", features = ["derive", "unstable-styles"] }
anyhow = "1.0"
anstyle = "1.0.1"
hex = "0.4.3"
regex = "1.9.5"

[dev-dependencies]
assert_cmd = "2.0.12"
indoc = "2.0.0"
